# OIDC configuration
oidc.clientId=${oidc.clientId}
oidc.clientSecret=${oidc.clientSecret}
oidc.clientName=${oidc.clientName}
oidc.providerUri=${oidc.providerUri}
oidc.providerLogOutUri=${oidc.providerLogOutUri}
oidc.logoutUri=${oidc.logoutUri}
oidc.redirectUri=${oidc.redirectUri}
oidc.loginUri=${oidc.loginUri}
oidc.callerGroupsClaim=${oidc.callerGroupsClaim}
oidc.audience=${oidc.audience}
