/**
 * Jenkins pipeline building SignServer, running unit tests and archives
 * the release artifact for other jobs to use.
 *
 * Additionally, test coverage is captured.
 */
pipeline {
    agent {
        dockerfile {
            label 'dss-docker'
            dir "jenkins-files/containers/${env.CONTAINER}"
            filename 'Dockerfile'
            additionalBuildArgs  '--disable-content-trust=false --pull'
            args '--user user --group-add root'
        }
    }

    stages {
        stage('Verify Environment') {
            steps {
                // Print versions
                sh "java -version"
                sh "mvn -version"
                sh "ant -version"
                sh "locale"
                sh "echo Workspace: ${WORKSPACE}"
                sh "printenv"
                sh "ls -l"

                // Init edition
                dir ('signserver') {
                    sh "ant -q init"

                    // Check expected edition
                    // TODO
                }
            }
        }
        stage('Build') {
            steps {
                dir ('signserver') {
                    sh "mvn -Dmaven.repo.local=${WORKSPACE}/m2-repo help:effective-settings"
                    sh "mvn -Dmaven.repo.local=${WORKSPACE}/m2-repo clean install -DskipTests"
                }
            }
        }
        stage('Unit Test') {
            steps {
                dir ('signserver') {
                    withEnv(['SIGNSERVER_NODEID=node1.example.com']) {                     
                        sh "mvn -Dmaven.repo.local=${WORKSPACE}/m2-repo test"

                        // gather the results
                        junit "**/target/surefire-reports/*.xml"
                    }
                }
            }
        }
        stage('Package') {
            steps {
                dir ('signserver') {
                    // Create the release
                    sh "ant release:binary-zip"
                }
                archiveArtifacts 'signserver-*-bin.zip'
            }
        }
        stage('Javadoc') {
            steps {
                dir ('signserver') {
                    // Build Javadoc
                    sh "mvn -Dmaven.repo.local=${WORKSPACE}/m2-repo javadoc:aggregate"
                }
            }
        }
        stage('Coverage') {
            steps {
                dir ('signserver') {
                    jacoco()
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}
