# Sample configuration of a Fortanix crypto worker
#

# Type of worker and implementation
WORKERGENID1.TYPE=CRYPTO_WORKER
WORKERGENID1.IMPLEMENTATION_CLASS=org.signserver.server.signers.CryptoWorker

# Uses an Azure cloud key vault
WORKERGENID1.CRYPTOTOKEN_IMPLEMENTATION_CLASS=org.signserver.server.enterprise.cryptotokens.FortanixCryptoToken

# Name for other workers to reference this worker:
WORKERGENID1.NAME=CryptoTokenFortanix


# The base URL for the Fortanix DSM REST API (optional)
WORKERGENID1.FORTANIX_BASE_ADDRESS=
#WORKERGENID1.FORTANIX_BASE_ADDRESS=https://apps.smartkey.io

# If a default key is configured, activation is tested by using the default key. If there is no configured default key,
# the activation is tested by a test connection to the Fortanix instance.
WORKERGENID1.DEFAULTKEY=testkey0
#WORKERGENID1.DEFAULTKEY=
