/*************************************************************************
 *                                                                       *
 *  SignServer: The OpenSource Automated Signing Server                  *
 *                                                                       *
 *  This software is free software; you can redistribute it and/or       *
 *  modify it under the terms of the GNU Lesser General Public           *
 *  License as published by the Free Software Foundation; either         *
 *  version 2.1 of the License, or any later version.                    *
 *                                                                       *
 *  See terms of license at gnu.org.                                     *
 *                                                                       *
 *************************************************************************/
package org.signserver.admin.gui;

import java.io.File;
import java.io.IOException;
import java.security.cert.Certificate;
import java.security.cert.CertificateException;
import java.security.cert.X509Certificate;
import java.util.Collection;
import java.util.Iterator;
import java.util.List;
import java.util.Vector;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;
import org.apache.log4j.Logger;
import org.ejbca.util.CertTools;
import org.signserver.common.GlobalConfiguration;
import org.signserver.common.WorkerStatus;

/**
 * Dialog for installing certificates to signers.
 *
 * @author markus
 * @version $Id$
 */
public class InstallCertificatesDialog extends javax.swing.JDialog {

    /** Logger for this class. */
    private static final Logger LOG
            = Logger.getLogger(InstallCertificatesDialog.class);

    public static final int CANCEL = 0;
    public static final int OK = 1;

    private static Vector<String> columnNames = new Vector<String>();
    static {
        columnNames.add("Signer");
        columnNames.add("Signer certificate");
        columnNames.add("Certificate chain");
    };

    private int resultCode = CANCEL;

    private MainView mainView;

    private List<Worker> signers;
    private Vector<Vector<String>> data;

    /** Creates new form InstallCertificatesDialog */
    public InstallCertificatesDialog(java.awt.Frame parent, boolean modal,
            MainView mainView, List<Worker> signers) {
        super(parent, modal);
        this.mainView = mainView;
        this.signers = signers;
        initComponents();
        setTitle("Install certificates for " + signers.size() + " signers");
        data = new Vector<Vector<String>>();
        for (int row = 0; row < signers.size(); row++) {
            Worker signer = signers.get(row);
            Vector<String> cols = new Vector<String>();
            cols.add(signer.getName() + " (" + signer.getWorkerId() + ")");
            cols.add("");
            cols.add("");
            data.add(cols);
        }
        jTable1.setModel(new DefaultTableModel(data, columnNames) {

            @Override
            public boolean isCellEditable(int row, int column) {
                return column > 0;
            }

        });
        jTable1.getModel().addTableModelListener(new TableModelListener() {

            @Override
            public void tableChanged(final TableModelEvent e) {
                boolean enable = true;
                for (int row = 0; row < jTable1.getRowCount(); row++) {
                    if ("".equals(jTable1.getValueAt(row, 1))
                            || "".equals(jTable1.getValueAt(row, 2))) {
                        enable = false;
                        break;
                    }
                }
                jButtonInstall.setEnabled(enable);
            }
        });

        final BrowseCellEditor editor = new BrowseCellEditor(new JTextField(),
                JFileChooser.OPEN_DIALOG);
        editor.setClickCountToStart(1);
        jTable1.getColumn("Signer certificate").setCellEditor(editor);
        jTable1.getColumn("Certificate chain").setCellEditor(editor);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButtonInstall = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(org.signserver.admin.gui.SignServerAdminGUIApplication.class).getContext().getResourceMap(InstallCertificatesDialog.class);
        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButtonInstall.setText(resourceMap.getString("jButtonInstall.text")); // NOI18N
        jButtonInstall.setEnabled(false);
        jButtonInstall.setName("jButtonInstall"); // NOI18N
        jButtonInstall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInstallActionPerformed(evt);
            }
        });

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Signer", "Signer certificate", "Certificate chain"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setName("jTable1"); // NOI18N
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 827, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 803, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonInstall)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 392, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonInstall)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
}//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonInstallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInstallActionPerformed
        final String hostname = null;

        for (int row = 0; row < data.size(); row++) {
            final Worker signer = signers.get(row);
            final int workerid = signer.getWorkerId();

            final File signerCertFile = new File(
                    (String) jTable1.getValueAt(row, 1));
            final File signerChainFile = new File(
                    (String) jTable1.getValueAt(row, 2));

            if (LOG.isDebugEnabled()) {
                LOG.debug("signer=" + workerid + "cert=\"" + signerCertFile
                        + "\", signerChainFile=\"" + signerChainFile +"\"");
            }

            try {

                final String scope = GlobalConfiguration.SCOPE_GLOBAL;

                Collection<Certificate> signerCerts = CertTools.getCertsFromPEM(
                        signerCertFile.getAbsolutePath());
                if(signerCerts.size() == 0){
                    JOptionPane.showMessageDialog(this, 
                            "Problem with signer certificate file for signer "
                            + workerid + ":\n" + "No certificate in file",
                            "Install certificates", JOptionPane.ERROR_MESSAGE);
                }
                if (signerCerts.size() != 1) {
                    // TODO: Warning more than one certificate
                }
                final X509Certificate signerCert
                        = (X509Certificate) signerCerts.iterator().next();

                Collection<Certificate> signerChain;

                try {
                    signerChain = CertTools.getCertsFromPEM(
                            signerChainFile.getAbsolutePath());
                    if(signerChain.size() == 0){
                        JOptionPane.showMessageDialog(this,
                            "Problem with certificate chain file for signer "
                            + workerid + ":\n" + "No certificates in file",
                            "Install certificates", JOptionPane.ERROR_MESSAGE);
                    }


                    Iterator<Certificate> iter = signerCerts.iterator();
                    while(iter.hasNext()){
                      X509Certificate cert = (X509Certificate) iter.next();
                        WorkerStatus.printCert(cert, System.out);
                        System.out.println("\n");
                    }

                    SignServerAdminGUIApplication.getWorkerSession()
                            .uploadSignerCertificateChain(workerid,
                                signerChain, scope);
                    SignServerAdminGUIApplication.getWorkerSession()
                            .uploadSignerCertificate(workerid, signerCert,
                            scope);
                    SignServerAdminGUIApplication.getWorkerSession()
                            .reloadConfiguration(workerid);

                    signers.remove(signer);
                    data.remove(row);
                    row--;
                    jTable1.revalidate();
                } catch (IOException ex) {
                    LOG.error("Problem with certificate chain file", ex);
                    JOptionPane.showMessageDialog(this, 
                            "Problem with certificate chain file for signer "
                            + workerid + ":\n" + ex.getMessage(),
                            "Install certificates", JOptionPane.ERROR_MESSAGE);
                } catch (CertificateException ex) {
                    LOG.error("Problem with certificate chain file", ex);
                    JOptionPane.showMessageDialog(this, 
                            "Problem with certificate chain file for signer "
                            + workerid + ":\n" + ex.getMessage(),
                            "Install certificates", JOptionPane.ERROR_MESSAGE);
                }

            } catch (IOException ex) {
                LOG.error("Problem with signer certificate file", ex);
                JOptionPane.showMessageDialog(this,
                        "Problem with signer certificate file for signer "
                        + workerid + ":\n" + ex.getMessage(),
                        "Install certificates", JOptionPane.ERROR_MESSAGE);
            } catch (CertificateException ex) {
                LOG.error("Problem with signer certificate file", ex);
                JOptionPane.showMessageDialog(this,
                        "Problem with signer certificate file for signer "
                        + workerid + ":\n" + ex.getMessage(),
                        "Install certificates", JOptionPane.ERROR_MESSAGE);
            }
        }
        if (jTable1.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this,
                    "All certificates installed. Please verify the installed ceritifcates before activating the signers.");
            dispose();
        }
    }//GEN-LAST:event_jButtonInstallActionPerformed

    public int getResultCode() {
        return resultCode;
    }

    public int showDialog() {
        setVisible(true);
        return resultCode;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonInstall;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
