# Sample configuration of an Azure Key Vault crypto worker
#

# Type of worker and implementation
WORKERGENID1.TYPE=CRYPTO_WORKER
WORKERGENID1.IMPLEMENTATION_CLASS=org.signserver.server.signers.CryptoWorker

# Uses an Azure cloud key vault
WORKERGENID1.CRYPTOTOKEN_IMPLEMENTATION_CLASS=org.signserver.server.cryptotokens.AzureKeyVaultCryptoToken

# Name for other workers to reference this worker:
WORKERGENID1.NAME=CryptoTokenAzureKeyVault

# Key vault name (required)
WORKERGENID1.KEY_VAULT_NAME=

# Key vault client ID (required)
WORKERGENID1.KEY_VAULT_CLIENT_ID=

# Key vault type (either of "standard", or "premium") (required)
WORKERGENID1.KEY_VAULT_TYPE=standard
#WORKERGENID1.KEY_VAULT_TYPE=premium

# Optional password (client credentials) for the key vault. If specified the token is "auto-activated".
#WORKERGENID1.PIN=replace-with-your-client-credentials

# If a default key is configured, activation is tested by using the default key. If there is no configured default key,
# the activation is tested by a test connection to the Azure Key Vault instance.
WORKERGENID1.DEFAULTKEY=testkey0
#WORKERGENID1.DEFAULTKEY=