-- TODO: Remove this file

--
-- These definitions should work for SignServer 3.2.x, Oracle 10.x and the JDBC driver version 10.2.0.1.0.
-- Version: $Id$
--

DROP TABLE "ARCHIVEDATA";

CREATE TABLE "ARCHIVEDATA" (
	"UNIQUEID" VARCHAR2(255 CHAR) NOT NULL, 
	"ARCHIVEDATA" CLOB, 
	"ARCHIVEID" VARCHAR2(255 CHAR), 
	"REQUESTCERTSERIALNUMBER" VARCHAR2(255 CHAR), 
	"REQUESTIP" VARCHAR2(255 CHAR), 
	"REQUESTISSUERDN" VARCHAR2(255 CHAR), 
	"SIGNERID" NUMBER(10,0) NOT NULL, 
	"TIME" NUMBER(19,0) NOT NULL, 
	"TYPE" NUMBER(10,0) NOT NULL, 
	PRIMARY KEY ("UNIQUEID")
);

DROP TABLE "BOOKDATABEAN";

CREATE TABLE "BOOKDATABEAN" (
	"NAME" VARCHAR2(255 CHAR) NOT NULL, 
	"COUNTER" NUMBER(10,0) NOT NULL, 
	PRIMARY KEY ("NAME")
);

DROP TABLE "CLUSTEREDCLASSES";

CREATE TABLE "CLUSTEREDCLASSES" (
	"ID" NUMBER(10,0) NOT NULL, 
	"COMMENT0" CLOB, 
	"DESCRIPTION" CLOB, 
	"IMPLINTERFACES" CLOB, 
	"JARNAME" VARCHAR2(255 CHAR) NOT NULL, 
	"MODULENAME" VARCHAR2(255 CHAR) NOT NULL, 
	"PART" VARCHAR2(255 CHAR) NOT NULL, 
	"RESOURCEDATA" BLOB NOT NULL, 
	"RESOURCENAME" VARCHAR2(255 CHAR) NOT NULL, 
	"TIMESTAMP" NUMBER(19,0) NOT NULL, 
	"TYPE" VARCHAR2(255 CHAR) NOT NULL, 
	"VERSION" NUMBER(10,0) NOT NULL, 
	PRIMARY KEY ("ID")
);

DROP TABLE "ENCKEYDATA";

CREATE TABLE "ENCKEYDATA" (
	"ID" NUMBER(19,0) NOT NULL, 
	"ENCKEYREF" VARCHAR2(255 CHAR), 
	"INUSE" NUMBER(1,0) NOT NULL, 
	"NUMBEROFENCRYPTIONS" NUMBER(19,0) NOT NULL, 
	"USAGEENDED" TIMESTAMP (6), 
	"USAGESTARTED" TIMESTAMP (6), 
	"WORKERID" NUMBER(10,0) NOT NULL, 
	PRIMARY KEY ("ID")
);

DROP TABLE "GLOBALCONFIG";

CREATE TABLE "GLOBALCONFIG" (
	"PROPERTYKEY" VARCHAR2(255 CHAR) NOT NULL, 
	"PROPERTYVALUE" CLOB, 
	PRIMARY KEY ("PROPERTYKEY")
);

DROP TABLE "GROUPKEYDATA";

CREATE TABLE "GROUPKEYDATA" (
	"ID" NUMBER(19,0) NOT NULL, 
	"CREATIONDATE" TIMESTAMP (6), 
	"DOCUMENTID" VARCHAR2(255 CHAR), 
	"ENCKEYREF" VARCHAR2(255 CHAR), 
	"ENCRYPTEDDATA" BLOB, 
	"FIRSTUSEDDATE" TIMESTAMP (6), 
	"LASTFETCHEDDATE" TIMESTAMP (6), 
	"WORKERID" NUMBER(10,0) NOT NULL, 
	PRIMARY KEY ("ID")
);

DROP TABLE "KEYUSAGECOUNTER";

CREATE TABLE "KEYUSAGECOUNTER" (
	"KEYHASH" VARCHAR2(255 CHAR) NOT NULL, 
	"COUNTER" NUMBER(19,0) NOT NULL, 
 	PRIMARY KEY ("KEYHASH")
);
 
DROP TABLE "SHELFDATABEAN";

CREATE TABLE "SHELFDATABEAN" (
	"NAME" VARCHAR2(255 CHAR) NOT NULL, 
	"COUNTER" NUMBER(10,0) NOT NULL, 
	PRIMARY KEY ("NAME")
);

DROP TABLE "SIGNERCONFIGDATA";

CREATE TABLE "SIGNERCONFIGDATA" (
	"SIGNERID" NUMBER(10,0) NOT NULL, 
	"SIGNERCONFIGDATA" CLOB, 
	PRIMARY KEY ("SIGNERID")
);

CREATE SEQUENCE "HIBERNATE_SEQUENCE"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1;
