/*************************************************************************
 *                                                                       *
 *  SignServer Enterprise - Proprietary Modules.                         *
 *                                                                       *
 *  Copyright (c), PrimeKey Solutions AB. All rights reserved.           *
 *  The use of the Proprietary Modules are subject to specific           *
 *  commercial license terms.                                            *
 *                                                                       *
 *************************************************************************/
/**
 * Jenkins pipeline for ad hoc testing/experimentation by Ram.
 *
 */
pipeline {
	agent {
		label "dss-docker"
	}
    
    stages {
        stage('build dss') {
            agent {
                // build and run (later also cleanup) the Docker container
                dockerfile {
                    label 'dss-docker'
                    dir 'jenkins-files/test'
                    filename 'Dockerfile'
                    additionalBuildArgs  '--disable-content-trust=false --pull'
                    args '--group-add root'
                }
            }
            steps {
                // Run these steps inside the running docker container
                dir ('signserver') {
                    //sh "cp /opt/conf/* conf/"
                    //sh "ant -q -Dappserver.home=/tmp -Dappserver.type=jboss -Dejbca.productionmode=false clean build test:runsa"
                    sh "ant -q init"
                    sh "mvn clean install -DskipTests"
                }
                // gather the results
                //junit "ejbca/**/reports/**/TEST-*.xml"
            }
        }
    }
    post {
        always {
            cleanWs()
        }
    }
}
