/**
 * Jenkins pipeline archiving a SignServer release file from the binaries 
 * folder.
 *
 * This pipeline can be used as un upstream job for other jobs that require a 
 * SignServer release. It was previously used during the time when the 
 * build was broken but we still wanted to work on the other jobs.
 */
node('dss-docker-slave') {

    checkout([$class: 'SubversionSCM', additionalCredentials: [], excludedCommitMessages: '', excludedRegions: '', excludedRevprop: '', excludedUsers: '', filterChangelog: false, ignoreDirPropChanges: false, includedRegions: '', locations: [[cancelProcessOnExternalsFail: true, credentialsId: 'e8aa0eb0-9eb8-42d2-8596-6a7a90c8f7cc', depthOption: 'infinity', ignoreExternalsOption: true, local: '.', remote: 'https://svn.cesecore.eu/svn/signserver-restricted/trunk']], quietOperation: true, workspaceUpdater: [$class: 'UpdateUpdater']])

        stage('Verify Environment') {
                // Print versions
                sh "java -version"
                sh "locale"
                sh "echo Workspace: ${WORKSPACE}"
                sh "printenv"
                sh "ls -l"
        }
        stage('Copy Release File') {
                sh ('cp /home/jenkins/binaries/signserver-ee-5.0.0.Alpha1-SNAPSHOT-bin.zip .')
                sh ('ls -l')
        }
        stage('Package') {
                archiveArtifacts 'signserver-*-bin.zip'
        }
}
